use std::path::PathBuf;
use crate::executor::{run_command, ExecutorError};

#[derive(Debug)]
pub struct GitExecutor {
    repo_path: PathBuf,
}

impl GitExecutor {
    /// Create new GitExecutor for the given output directory
    pub fn new(repo_path: PathBuf) -> Self {
        Self { repo_path }
    }
    
    /// Initialize git repo if needed
    pub fn init_or_verify(&self) -> Result<(), ExecutorError> {
        let git_dir = self.repo_path.join(".git");
        if git_dir.exists() && git_dir.is_dir() {
            // Verify it's a valid repo
            run_command(&["git", "status"], Some(&self.repo_path))?;
            Ok(())
        } else {
            // Initialize new repo
            run_command(&["git", "init"], Some(&self.repo_path))?;
            Ok(())
        }
    }
    
    /// Stage all generated files
    pub fn stage_all(&self) -> Result<(), ExecutorError> {
        run_command(&["git", "add", "."], Some(&self.repo_path))?;
        Ok(())
    }
    
    /// Create commit with generated configs
    pub fn commit_configs(
        &self,
        hostname: &str,
        username: &str,
    ) -> Result<(), ExecutorError> {
        let message = format!(
            "milos: Generate {} config for {}\n\nGenerated by milos_niri installer",
            hostname, username
        );
        run_command(&["git", "commit", "-m", &message], Some(&self.repo_path))?;
        Ok(())
    }
    
    /// Get the current commit hash (for rollback reference)
    pub fn get_current_commit(&self) -> Result<Option<String>, ExecutorError> {
        let output = run_command(&["git", "rev-parse", "HEAD"], Some(&self.repo_path))?;
        Ok(Some(output.stdout.join("").trim().to_string()))
    }
    
    /// Check if directory is a git repository
    pub fn is_repo(&self) -> bool {
        self.repo_path.join(".git").exists() && self.repo_path.join(".git").is_dir()
    }
    
    /// Get list of staged/unstaged files
    pub fn get_status(&self) -> Result<Vec<String>, ExecutorError> {
        let output = run_command(&["git", "status", "--porcelain"], Some(&self.repo_path))?;
        Ok(output.stdout)
    }
    
    /// Verify git is installed
    pub fn git_available() -> bool {
        run_command(&["git", "--version"], None).is_ok()
    }
}
