//! # Generator Module
//! Handles configuration file generation from user-provided templates.
//!
//! This module provides the infrastructure for rendering and writing
//! NixOS configuration files based on the user's collected input.

pub mod flake;
pub mod users;
pub mod git;
pub mod locale;
pub mod noctalia;
pub mod niri;
pub mod nixconf;

pub use self::error::GeneratorError;
pub use self::context::UserConfig;

/// Represents a generated file with its path and content.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    /// The relative path where the file should be written.
    pub path: std::path::PathBuf,
    /// The content of the generated file.
    pub content: String,
}

/// The Generator trait defines the interface for all configuration generators.
///
/// Each generator is responsible for producing one or more configuration files
/// based on the user configuration. Generators render templates and return
/// the generated content along with the target output path.
pub trait Generator {
    /// Generate the configuration file(s) for this generator.
    ///
    /// # Arguments
    /// * `config` - The user configuration to use for generation.
    ///
    /// # Returns
    /// A `Result` containing either a single `GeneratedFile` or a vector of
    /// `GeneratedFile`s, or a `GeneratorError` if generation fails.
    fn generate(&self, config: &UserConfig) -> Result<Vec<GeneratedFile>, GeneratorError>;

    /// Get the base output path for files generated by this module.
    ///
    /// # Arguments
    /// * `config` - The user configuration to use for path determination.
    ///
    /// # Returns
    /// The base `PathBuf` where generated files should be written.
    fn output_base_path(&self, config: &UserConfig) -> std::path::PathBuf;
}
